### PR TITLE
Template column implementation

### PR DESCRIPTION
**Pull request by PurpleGray**
Hello, for my project needs I added DataGridTemplateColumn implementation in my fork.
Also updated sample (replaced one column type from Text to Template) + updated dependencies.

### CODE REVIEW

**Comment by ahopper** [comment]
I've been trying this and it is working well with templates with StackPanels, TextBlocks and Borders but controls like Button and CheckBox don't seem to render.  I've been using with dependencies updated to v0.6.2-build6147-beta

**Comment by PurpleGray** [comment]
can approve what @ahopper said
but yet haven't time to find out why it doesn't work well
may be someone has ideas

**Comment by sdoroff** [comment]
Sorry for the slow response on this. I due to some implementation details necessary to make the `DataGrid` work with Avalonias validation system, the `DataGridTemplateColumn` should inherit from `DataGridColumn` and not `DataGridBoundColumn`

**Comment by PurpleGray** [comment]
I've tried to change class inheritance for DataGridTemplateColumn from DataGridBoundColumn to DataGridColumn, but it didnt solved the problem :(

**Comment by danwalmsley** [comment]
@PurpleGray @sdoroff could be an issue in Avalonia itself? do those controls make it to visual tree?

**Comment by ahopper** [comment]
Is it worth merging this (maybe with the inheritance sorted) just to make it easier to play with and test and encourage some more input?

**Comment by danwalmsley** [comment]
@ahopper id be happy with that

**Comment by sdoroff** [comment]
Sorry I've been away from this for a while. I just added an implementation of the DataGridTemplateColumn. It seems to now render all controls correctly. I'm closing this pull request.

**Pull request closed without merging**
